name: healthy
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  intl: ^0.19.0
  cloud_firestore: ^5.0.2
  shared_preferences: ^2.2.3
  internet_connection_checker_plus: ^2.5.0
  connectivity_plus: ^6.0.3
  firebase_storage: ^12.1.0
  firebase_database: ^11.0.2
  image_picker: ^1.1.2
  animated_segmented_tab_control: ^2.0.0
  file_picker: ^8.0.5
  easy_pdf_viewer: ^1.0.8
  quick_actions: ^1.0.7
  gallery_picker: ^0.5.1
  photo_view: ^0.15.0
  table_calendar: ^3.1.2
  firebase_messaging: ^15.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true
  assets:
   - assets/background/
   - assets/images/emailver/
   - assets/images/user/
   - assets/images/home/