name: healthy
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  intl: ^0.19.0
  cloud_firestore: ^4.17.2
  shared_preferences: ^2.2.3
  internet_connection_checker_plus: ^2.5.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true
  assets:
   - assets/background/
   - assets/images/emailver/