// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn9XwilZseRDZWXHjxHwht3huuQK5Ckrc',
    appId: '1:243307408733:web:077c76301f2c31db328cb4',
    messagingSenderId: '243307408733',
    projectId: 'healthytime-3f6b8',
    authDomain: 'healthytime-3f6b8.firebaseapp.com',
    storageBucket: 'healthytime-3f6b8.appspot.com',
    measurementId: 'G-N5FYB2NN6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN6w1N6btf8clyyeGSbyw2BKbNBGAC4Pc',
    appId: '1:243307408733:android:5a6f691481b6c7aa328cb4',
    messagingSenderId: '243307408733',
    projectId: 'healthytime-3f6b8',
    storageBucket: 'healthytime-3f6b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJHYnzCRy2cTojQiehcOUoT8LhlCJHHNI',
    appId: '1:243307408733:ios:24234a1856d9a8c5328cb4',
    messagingSenderId: '243307408733',
    projectId: 'healthytime-3f6b8',
    storageBucket: 'healthytime-3f6b8.appspot.com',
    iosBundleId: 'com.example.healthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJHYnzCRy2cTojQiehcOUoT8LhlCJHHNI',
    appId: '1:243307408733:ios:24234a1856d9a8c5328cb4',
    messagingSenderId: '243307408733',
    projectId: 'healthytime-3f6b8',
    storageBucket: 'healthytime-3f6b8.appspot.com',
    iosBundleId: 'com.example.healthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn9XwilZseRDZWXHjxHwht3huuQK5Ckrc',
    appId: '1:243307408733:web:379a08f8cacd9807328cb4',
    messagingSenderId: '243307408733',
    projectId: 'healthytime-3f6b8',
    authDomain: 'healthytime-3f6b8.firebaseapp.com',
    storageBucket: 'healthytime-3f6b8.appspot.com',
    measurementId: 'G-CZF3B9YQTL',
  );
}
